// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");

function ServiceFunctor(C) {
  var apply = function (arg) {
    return Curry._1(C.execute, arg) + "Functor";
  };
  return {
          apply: apply
        };
}

function Application(S) {
  var run = function (arg) {
    return Curry._1(S.apply, arg) + "Application";
  };
  return {
          run: run
        };
}

var $$class = CamlinternalOO.create_table([
      "serviceA",
      "serviceB"
    ]);

var ids = CamlinternalOO.get_method_labels($$class, [
      "serviceB",
      "serviceA"
    ]);

var serviceB = ids[0];

var serviceA = ids[1];

CamlinternalOO.set_methods($$class, [
      serviceA,
      (function (self$1, value) {
          return 0 + value | 0;
        }),
      serviceB,
      (function (self$1, value) {
          return 100 + value | 0;
        })
    ]);

CamlinternalOO.init_class($$class);

var depmodules = CamlinternalOO.create_object_opt(undefined, $$class);

exports.ServiceFunctor = ServiceFunctor;
exports.Application = Application;
exports.depmodules = depmodules;
/* class Not a pure module */
