// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Id = /* @__PURE__ */Caml_exceptions.create("HeaderSoftwear-ReactTemplate.Id");

var Name = /* @__PURE__ */Caml_exceptions.create("HeaderSoftwear-ReactTemplate.Name");

var Author = /* @__PURE__ */Caml_exceptions.create("HeaderSoftwear-ReactTemplate.Author");

var CreatedAt = /* @__PURE__ */Caml_exceptions.create("HeaderSoftwear-ReactTemplate.CreatedAt");

exports.Id = Id;
exports.Name = Name;
exports.Author = Author;
exports.CreatedAt = CreatedAt;
/* No side effect */
