// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Id = /* @__PURE__ */Caml_exceptions.create("HeaderUser-ReactTemplate.Id");

var Name = /* @__PURE__ */Caml_exceptions.create("HeaderUser-ReactTemplate.Name");

var Age = /* @__PURE__ */Caml_exceptions.create("HeaderUser-ReactTemplate.Age");

var Gender = /* @__PURE__ */Caml_exceptions.create("HeaderUser-ReactTemplate.Gender");

exports.Id = Id;
exports.Name = Name;
exports.Age = Age;
exports.Gender = Gender;
/* No side effect */
