// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var A = /* @__PURE__ */Caml_exceptions.create("ReportHeader-ReactTemplate.A");

var B = /* @__PURE__ */Caml_exceptions.create("ReportHeader-ReactTemplate.B");

var C = /* @__PURE__ */Caml_exceptions.create("ReportHeader-ReactTemplate.C");

var D = /* @__PURE__ */Caml_exceptions.create("ReportHeader-ReactTemplate.D");

var E = /* @__PURE__ */Caml_exceptions.create("ReportHeader-ReactTemplate.E");

var F = /* @__PURE__ */Caml_exceptions.create("ReportHeader-ReactTemplate.F");

exports.A = A;
exports.B = B;
exports.C = C;
exports.D = D;
exports.E = E;
exports.F = F;
/* No side effect */
