// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function applyUser(apply, user) {
  return Curry._1(apply, user._0);
}

var Sample = {};

exports.applyUser = applyUser;
exports.Sample = Sample;
/* No side effect */
