// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");

function withDefault($$default, op) {
  if (op !== undefined) {
    return Caml_option.valFromOption(op);
  } else {
    return $$default;
  }
}

var $$Option = {
  withDefault: withDefault
};

function contain(target, search) {
  return new RegExp(search).test(target);
}

var $$String = {
  contain: contain
};

exports.$$Option = $$Option;
exports.$$String = $$String;
/* No side effect */
