// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function ModalFooter(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "modal-footer"
            }, children);
}

var make = ModalFooter;

exports.make = make;
/* react Not a pure module */
