// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function ModalHeader(Props) {
  var title = Props.title;
  var children = Props.children;
  return React.createElement("div", {
              className: "modal-header"
            }, React.cloneElement(title, {
                  className: "modal-title"
                }), children);
}

var make = ModalHeader;

exports.make = make;
/* react Not a pure module */
