// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function ModalBody(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "modal-body"
            }, children);
}

var make = ModalBody;

exports.make = make;
/* react Not a pure module */
