// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function showAnimalCharacterInfo(animal) {
  if (animal.TAG === /* Cat */0) {
    return String(animal._0.pattern);
  } else {
    return animal._0.skill;
  }
}

function showAnimalHeight(animal) {
  return animal.height;
}

exports.showAnimalCharacterInfo = showAnimalCharacterInfo;
exports.showAnimalHeight = showAnimalHeight;
/* No side effect */
